spring:
  application:
    name: DevSquard
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/devsqaurd_db
    username: root
    password: 1234
  jpa:
    generate-ddl: true
    show-sql:  true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
  sql:
    init:
      mode: never
  upload:
    location: C://Users//WD//Desktop//post-image
# 스웨거 설정
  mvc:
    pathmatch:
      matching-strategy: ant-path-matcher